services:
#    rb_bolt.example:
#        class: RB\BoltBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    rb_bolt.extension:
        class: RB\BoltBundle\Twig\BoltExtension
        arguments: ["@service_container", "@twig", "@session"]
        tags:
            - { name: twig.extension }
    rb_bolt.services:
        class: RB\BoltBundle\Services\BoltService
        arguments: ["@service_container", "@session", "@router"]

    rb_bolt.route_type:
        class: RB\Bolt\Form\Type\RouteType
        arguments: ["@service_container", "@session", "@router"]
        calls:
          - [setContainer, ['@service_container']]
        tags:
            - { name: form.type, alias: 'container' }