<?php

namespace RB\BoltBundle\Repository;

/**
 * BoltRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoltRepository extends \Doctrine\ORM\EntityRepository
{
}
